GMBP-97: Allow RMI (Api) to build and run tests within Jenkins
Crown-Commercial-Service/DataSubmissionServiceAPI pull request #1015
Opened 2023-09-06 09:42 UTC by georgeschena

## Description
This allows us to build a docker image and run those tests from a single command `docker-tests.sh`
https://crowncommercialservice.atlassian.net/browse/GMBP-97

## Why was the change made?
So we can run tests within Jenkins

2023-09-06 12:44 UTC, mcbhenwood requested changes

2023-09-06 12:44 UTC, mcbhenwood commented on docker-tests.sh
> +docker compose --file docker-compose.test.yml --env-file docker-compose.env up -d test
We should probably spin down the containers when the script exits

2023-09-07 11:36 UTC, reemi1510 commented on docker-compose.build.yml
Where is this used?

2023-09-07 11:36 UTC, reemi1510 commented on docker-tests.sh
This is very similar to existing rake tasks, do we need to repeat code?

2023-09-22 08:03 UTC, reemi1510 approved these changes

2023-09-22 08:03 UTC, merged